### ISSUE TITLE
Interested to maintain the gem

### ISSUE THREAD

**Issue by albabar** [simi/omniauth-facebook#334] opened 2020-01-15 05:06 UTC
Dear @mkdynamic and other maintainers,

I'm a frequent user of this gem. Most of the project I worked on till now, this was an essential part. You guys really did a great job creating and maintaining this gem. We really appreciate it as a community.

I can understand life happens, priorities change, and someone cannot focus on the same thing all the time.

I'm really interested in taking the wheel and maintaining the gem until life happens to me as well! Looking forward to hearing from you guys.

**Comment by simi** [comment] 2020-01-15 07:57
Hello, I'm still actively maintaining this.

Maintaining issues is a little painful since it is really hard to reproduce some issues reported.

If you would like to help, it will be nice if you can take a look at some issues and pull requests.

PS: There are some issues related to  FB API version used. I'm trying to keep it backwards compatible as possible and you can still use any API you need by specifying version manually - https://github.com/mkdynamic/omniauth-facebook#api-version.

Feel free to ping me if any help is needed.

**Comment by albabar** [comment] 2020-01-15 08:09
Thanks @simi for your prompt response. I saw the notice on the `README.md` file and thought you guys were looking for someone.

Okay, I'll definitely try to look into some issues as soon as possible. :)

**Comment by simi** [comment] 2020-01-15 08:22
Any help is appreciated. We're in the middle of moving this repo to me. Once done I can make you maintainer as well.

**Closed** 2020-02-21 00:04 UTC
Labels: no-issue-activity
