### ISSUE TITLE
execution expired

### ISSUE THREAD

**Issue by fabiancarlos** [simi/omniauth-facebook#283] opened 2017-08-11 18:11 UTC
Depending on my network connection i can't connect with the facebook, or dont receive the response. I just cant debugg this. Partial of my stacktrace:

```
Faraday::ConnectionFailed - execution expired:
  /Users/fabiancarlos/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:880:in `initialize'
  /Users/fabiancarlos/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:880:in `open'
  /Users/fabiancarlos/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:880:in `block in connect'
  /Users/fabiancarlos/.rbenv/versions/2.3.3/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
  /Users/fabiancarlos/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:878:in `connect'
  /Users/fabiancarlos/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
  /Users/fabiancarlos/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:852:in `start'
  /Users/fabiancarlos/.rbenv/versions/2.3.3/lib/ruby/2.3.0/net/http.rb:1398:in `request'
  faraday (0.11.0) lib/faraday/adapter/net_http.rb:80:in `perform_request'
  faraday (0.11.0) lib/faraday/adapter/net_http.rb:38:in `block in call'
  faraday (0.11.0) lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
  faraday (0.11.0) lib/faraday/adapter/net_http.rb:33:in `call'
  faraday (0.11.0) lib/faraday/request/url_encoded.rb:15:in `call'
  faraday (0.11.0) lib/faraday/rack_builder.rb:139:in `build_response'
  faraday (0.11.0) lib/faraday/connection.rb:377:in `run_request'
  oauth2 (1.3.1) lib/oauth2/client.rb:99:in `request'
  oauth2 (1.3.1) lib/oauth2/client.rb:146:in `get_token'
  oauth2 (1.3.1) lib/oauth2/strategy/auth_code.rb:30:in `get_token'
  omniauth-oauth2 (1.4.0) lib/omniauth/strategies/oauth2.rb:89:in `build_access_token'
  omniauth-facebook (4.0.0) lib/omniauth/strategies/facebook.rb:110:in `build_access_token'
  omniauth-oauth2 (1.4.0) lib/omniauth/strategies/oauth2.rb:73:in `callback_phase'
  omniauth-facebook (4.0.0) lib/omniauth/strategies/facebook.rb:67:in `block in callback_phase'
  omniauth-facebook (4.0.0) lib/omniauth/strategies/facebook.rb:131:in `with_authorization_code!'
  omniauth-facebook (4.0.0) lib/omniauth/strategies/facebook.rb:66:in `callback_phase'
  omniauth (1.6.1) lib/omniauth/strategy.rb:230:in `callback_call'
  omniauth (1.6.1) lib/omniauth/strategy.rb:187:in `call!'
  omniauth (1.6.1) lib/omniauth/strategy.rb:167:in `call'
  bullet (5.1.1) lib/bullet/rack.rb:12:in `call'
  rack (2.0.1) lib/rack/deflater.rb:35:in `call'
  warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
  warden (1.2.7) lib/warden/manager.rb:35:in `catch'
  warden (1.2.7) lib/warden/manager.rb:35:in `call'
```

**Comment by LeandroTk** [comment] 2017-09-11 18:15
:+1

I'm also having the same problem: `execution expired`

..depending on my network connection.

**Comment by fabiancarlos** [comment] 2017-09-11 18:36
@LeandroTk I was searching about, and be some issue with ssl, but i'cant find a way to deggut it.

**Comment by vermaxik** [comment] 2017-09-21 20:55
@LeandroTk @fabiancarlos have the same issue. Did you find way to fix it? I used the advices from https://github.com/mkdynamic/omniauth-facebook/issues/31:  disabled IPv6, removed saving images, added certificates, but it doesn't work for me.

**Comment by LeandroTk** [comment] 2017-09-21 22:35
@vermaxik Actually I didn't fix it. I just change the network when I need to login via Facebook and it worked for me.

**Comment by richardrails** [comment] 2018-01-10 13:57
+1

**Comment by gingerlime** [comment] 2019-03-09 12:46
Started bumping into this all of a sudden 24 hours ago or so... We've had over 100 instances of this error in the last 24 hours or so. Looks like some network issue, maybe even someone on Facebook's end (we use omniauth with google, and didn't see any errors there). Just curious if it's something others bump into right now.

**Comment by javiercr** [comment] 2019-03-11 08:47
@gingerlime we're experiencing the same here for the last 48 hours :/

**Comment by gingerlime** [comment] 2019-03-11 10:08
We're also hosted on Google (in Belgium)! Interesting...

**Comment by simi** [comment] 2019-03-11 12:16
Hello, would you mind if I close this issue? Feel free to discuss your problems in here, but there's nothing we can do about that in codebase if I understand it well since it is connection/network problem.

**Comment by gingerlime** [comment] 2019-03-11 12:26
Yes, I understand... But this seems like the only place to find out if others are experiencing such issues.

Are there any settings to extend the wait timeout though? this can be useful in some circumstances, or maybe auto-retry if it fails? (this is something that this gem can help with, I believe).

**Comment by simi** [comment] 2019-03-11 12:31
I think you should use our own retry mechanism since there's no general approach fitting all needs. Personally I use https://github.com/ooyala/retries gem to wrap code to handle retries on 3rd party services.

**Comment by gingerlime** [comment] 2019-03-11 12:51
The gem looks really cool. Thanks @simi !

Any particular reason not to incorporate it within omniauth-facebook though (maybe with a default of 1 retry would make the most sense and is backwards compatible)? or how would you recommend using it together with omniauth-facebook?

**Comment by simi** [comment] 2019-03-11 13:53
I think it is not good idea to couple this gem with retrying mechanism as I wrote before. If you're facing some problem as in first post stacktrace, you can just use retries gem with to retry on `Faraday::ConnectionFailed` exception.

Just find a line (mentioned as `call_fb_line` in example code) in your app raising this exception and wrap it as stated at https://github.com/ooyala/retries#custom-exceptions.

```ruby
with_retries(:max_tries => 3, :rescue => [Faraday::ConnectionFailed]) do
   call_fb_line
end
```

**Comment by gingerlime** [comment] 2019-03-11 13:58
Thanks @simi, but I'm not talking about my own code here, but rather about `omniauth-facebook`. So when I include the gem and configure it, I'm not sure where to set up retries... I guess I'm missing something obvious here, but I'm not sure how to do it.


Also, I understand that you think it's not a good idea, but could you explain why? A retry default of 1 would keep backwards compatibility, and still allow people to configure a variable retry, which I think can be a good thing (unless, it's trivial to use the retries gem, but see above, I'm still not sure how).

**Comment by simi** [comment] 2019-03-11 14:05
This gem provides only strategy for facebook for https://github.com/omniauth/omniauth build on top of https://github.com/omniauth/omniauth-oauth2 which is build on top of https://github.com/oauth-xx/oauth2. If you think retrying mechanism should be part of omniauth itself, please open issue in there. Can you reproduce the same problem with example app in example directory? If I remember well on problems `/auth/failed` should be called instead of rasing the exception. That's the way how to handle problems properly via omniauth. You should prepare friendly page asking users to try later for example or retry in there probably.

**Comment by javiercr** [comment] 2019-03-11 15:46
@gingerlime we're also in Google Cloud Belgium (europe-west1), so probably it was a connectivity issue from GCP to Facebook. We haven't experienced there error again for the last few hours.

I like @simi's suggestio nof using `retry`, we'll give it a try. Thank you!

**Comment by gingerlime** [comment] 2019-03-12 10:56
@javiercr Out last occurrence was 2019-03-10 06:37 am UTC

I'm not sure I fully understand how to use `retries`, but I guess I'll have to dig a bit deeper. We've been using omniauth with facebook/google without really understanding how things work. @javiercr if you have any tips, I'd be happy to hear :)

Thanks again @simi for the links and suggestion. Much appreciated.

**Comment by gmdmartin** [comment] 2019-07-11 00:40
Don't use retries. This happened to us (the provider is irrelevant). We blocked IP addresses ranges due to getting attacks from different countries/networks. Turns out Facebook uses one of those networks. So check your ACLs in your servers/firewalls/VPCs/etc. and try disabling them to find the network being blocked.

**Closed** 2020-01-29 00:02 UTC
Labels: no-issue-activity

**Comment by Tashows** [comment] 2022-01-21 15:54
I am experiencing the same issue. I've figured out that the problem ONLY occurs when the facebook-omniauth process starts and then ANOTHER request is made to the app, before the facebook callback is received. Once it is actually received this error is thrown: omniauth: (facebook) Authentication failure! execution expired. Any clues about concurrency issues?
